### ISSUE TITLE
Possibillity to give a token from cloudflare zero trust dashboard 

### ISSUE THREAD

**Issue by delta-whiplash** [UWUplus/flask-cloudflared#11]
Hello thanks for this amazing project 
how Can I forward my flask app to my own domain ?

**Comment by UWUplus** [comment]
I've looked into it, but it seems like this is not possible anymore with out a config. 
Or do you have another way that just uses additional command parameters that I haven't found?

**Comment by xdevfaheem** [comment]
@UWUplus is there any way to make the url persistent?

**Comment by UWUplus** [comment]
> @UWUplus is there any way to make the url persistent?

Hi, at this point in time there is no way to get persistent domains, as this is not in the scope of TryCloudflare but would require an own domain and a setup through Cloudflare Access. 
If you are interested in exploring this, be sure to reply here, if you find anything that might help to use own domains. 

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/

**Comment by xdevfaheem** [comment]
Sure, I'm on that!

**Comment by UWUplus** [comment]
Hi @delta-whiplash and @TheFaheem,
I've added an option for custom tunnel urls, please try the latest update by installing it locally.
Check here for more information: https://github.com/UWUplus/flask-cloudflared#custom-tunnel-domain.
I'm currently testing myself and hope to release this update to PyPI soon.

Thanks a lot!

**Comment by UWUplus** [comment]
I have now pushed this update to PyPI.

**Comment by xdevfaheem** [comment]
> I have now pushed this update to PyPI.

Thanks a lot my friend!
